<?php

namespace App\Libraries;

require_once APPPATH . "ThirdParty/stripe/vendor/autoload.php";

use Stripe\Stripe as StripeSDK;
use Stripe\Checkout\Session;
use Stripe\Subscription;
use Stripe\Product;
use Stripe\Price;
use Stripe\Exception\ApiErrorException;
use Stripe\Exception\SignatureVerificationException;
use Stripe\Webhook;
use UnexpectedValueException;

/**
 * Stripe Integration Library
 *
 * Handles Stripe Checkout Sessions for both one-time payments and subscriptions,
 * subscription cancellations, webhook signature verifications, and dynamic
 * singleton product/price generation via the Stripe REST API.
 * All API exceptions are intentionally allowed to bubble up or logged internally.
 */
class Stripe
{
    /**
     * @var string The Stripe secret key.
     */
    private string $secretKey;

    /**
     * @var string The Stripe webhook secret for signature verification.
     */
    private string $webhookSecret;

    /**
     * @var string The application name displayed on the checkout page.
     */
    private string $appName;

    /**
     * Initializes the Stripe SDK configuration.
     *
     * @param object $config Gateway configuration object containing secret_key and webhook_secret.
     * @param string $appName Name of the application for display purposes on Stripe Checkout.
     */
    public function __construct(object $config, string $appName = 'Varient')
    {
        $this->secretKey = $config->secret_key ?? '';
        $this->webhookSecret = trim($config->webhook_id ?? $config->webhook_secret ?? '');
        $this->appName = $appName;

        if (!empty($this->secretKey)) {
            StripeSDK::setApiKey($this->secretKey);
        }
    }

    /**
     * Creates a Stripe Checkout Session for both One-Time Payments and Subscriptions.
     *
     * @param object $paymentData Object containing order details (orderToken, totalAmount, currencyCode, isSubscription, planId, successUrl, cancelUrl).
     * @return string|null The Stripe Checkout URL to redirect the user to, or null if session URL is missing.
     * @throws ApiErrorException If the Stripe API request fails.
     */
    public function createCheckoutSession(object $paymentData): ?string
    {
        // Base session configuration
        $sessionConfig = [
            'payment_method_types' => ['card'],
            'success_url'          => $paymentData->successUrl,
            'cancel_url'           => $paymentData->cancelUrl,
            // Metadata acts as our reference payload for webhook processing.
            'metadata'             => [
                'order_token'     => $paymentData->orderToken ?? '',
                'is_subscription' => $paymentData->isSubscription ?? 0
            ]
        ];

        // Handle Subscription Mode
        if (isset($paymentData->isSubscription) && $paymentData->isSubscription == 1) {
            $sessionConfig['mode'] = 'subscription';
            $sessionConfig['line_items'] = [[
                'price'    => $paymentData->planId, // Must be a valid Stripe Price ID generated by createDynamicSubscriptionPlan
                'quantity' => 1,
            ]];
        } // Handle One-Time Payment Mode
        else {
            $sessionConfig['mode'] = 'payment';
            $sessionConfig['line_items'] = [[
                'price_data' => [
                    'currency'     => strtolower($paymentData->currencyCode ?? 'usd'),
                    'product_data' => [
                        'name'        => $this->appName . ' Order #' . ($paymentData->orderToken ?? ''),
                        'description' => trans("reference") . ': ' . ($paymentData->orderToken ?? ''),
                    ],
                    // Stripe expects amounts in cents
                    'unit_amount'  => (int)round(($paymentData->totalAmount ?? 0) * 100),
                ],
                'quantity'   => 1,
            ]];
        }

        $session = Session::create($sessionConfig);

        return $session->url ?? null;
    }

    /**
     * Retrieves a Stripe Checkout Session by its ID.
     * Useful for verifying payment status upon user return.
     *
     * @param string $sessionId The Stripe Checkout Session ID.
     * @return Session|null The session object, or null on failure.
     */
    public function getCheckoutSession(string $sessionId): ?Session
    {
        try {
            return Session::retrieve($sessionId);
        } catch (ApiErrorException $e) {
            log_message('error', '[Stripe Session Retrieve Error] ' . $e->getMessage());
            return null;
        }
    }

    /**
     * Cancels an active Stripe subscription immediately.
     *
     * @param string $subscriptionId The Stripe Subscription ID.
     * @return bool True on success, false on failure.
     */
    public function cancelSubscription(string $subscriptionId): bool
    {
        try {
            $subscription = Subscription::retrieve($subscriptionId);
            $subscription->cancel();
            return true;
        } catch (ApiErrorException $e) {
            log_message('error', '[Stripe Cancel Error] ' . $e->getMessage());
            return false;
        }
    }

    /**
     * Verifies the Stripe Webhook signature and returns the Event object.
     * Protects against replay attacks and spoofed webhook payloads.
     *
     * @param string $payload The raw JSON payload from the request body.
     * @param string $sigHeader The HTTP_STRIPE_SIGNATURE header value.
     * @return \Stripe\Event|null The verified Stripe Event object, or null on failure.
     */
    public function verifyWebhookSignature(string $payload, string $sigHeader): ?\Stripe\Event
    {
        if (empty($this->webhookSecret)) {
            log_message('error', '[Stripe Webhook] Missing Webhook Secret Key.');
            return null;
        }

        try {
            return Webhook::constructEvent(
                $payload,
                $sigHeader,
                $this->webhookSecret
            );
        } catch (UnexpectedValueException $e) {
            log_message('error', '[Stripe Webhook] Invalid payload structure.');
            return null;
        } catch (SignatureVerificationException $e) {
            log_message('error', '[Stripe Webhook] Signature verification failed.');
            return null;
        }
    }

    /**
     * Creates a main generic product on Stripe.
     * This acts as the singleton base for all dynamic recurring prices
     * and should only be called once per tenant installation.
     *
     * @param string $appName The name of the application
     * @return string|null The generated Product ID (starts with 'prod_')
     */
    public function createMainProduct(string $appName): ?string
    {
        $safeName = preg_replace('/[^A-Za-z0-9 ]/', '', $appName);
        if (empty(trim($safeName))) {
            $safeName = 'Premium';
        }

        $finalName = substr($safeName . ' Subscriptions', 0, 127);

        try {
            $product = Product::create([
                'name'        => $finalName,
                'description' => 'Main product for handling dynamic subscriptions.',
                'type'        => 'service',
            ]);

            return $product->id;
        } catch (ApiErrorException $e) {
            log_message('error', '[Stripe Main Product Creation Error] ' . $e->getMessage());
            return null;
        }
    }

    /**
     * Creates a dynamic Stripe recurring price attached to the main product.
     * In Stripe, "Prices" are equivalent to PayPal's "Billing Plans".
     *
     * @param string $productId The dynamic base product ID from the database (starts with 'prod_')
     * @param string $name Name of the specific plan (metadata only for internal tracking)
     * @param float $amount The total checkout amount
     * @param string $currency The currency code (e.g., 'usd')
     * @param string $interval Billing cycle interval ('day', 'week', 'month', 'year')
     * @return string|null      The generated Price ID (starts with 'price_')
     */
    public function createDynamicSubscriptionPlan(
        string $productId,
        string $name,
        float  $amount,
        string $currency,
        string $interval = 'month'
    ): ?string
    {
        if (empty($productId)) {
            return null;
        }

        try {
            $price = Price::create([
                'product'     => $productId,
                // Stripe requires amounts in the smallest currency unit (e.g., cents)
                'unit_amount' => (int)round($amount * 100),
                'currency'    => strtolower($currency),
                'recurring'   => [
                    'interval' => strtolower($interval),
                ],
                // Store the custom name in metadata for dashboard visibility
                'metadata'    => [
                    'plan_name' => $name
                ]
            ]);

            return $price->id;
        } catch (ApiErrorException $e) {
            log_message('error', '[Stripe Dynamic Price Creation Error] ' . $e->getMessage());
            return null;
        }
    }
}