<?php

namespace Config;

use CodeIgniter\Config\BaseConfig;

class Currencies extends BaseConfig
{
    public static array $currencies = [
        'USD' => ['name' => 'US Dollar', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => ',', 'thousand_sep' => '.'],
        'EUR' => ['name' => 'Euro', 'symbol' => '€', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'CAD' => ['name' => 'Canada Dollar', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'AED' => ['name' => 'UAE Dirham', 'symbol' => 'د.إ', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'AFN' => ['name' => 'Afghanistan Afghani', 'symbol' => 'Af', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'ALL' => ['name' => 'Albania Lek', 'symbol' => 'Lek', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'AMD' => ['name' => 'Armenian Dram', 'symbol' => 'AMD', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'ANG' => ['name' => 'Netherlands Antilles Guilder', 'symbol' => 'ƒ', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'AOA' => ['name' => 'Kwanza', 'symbol' => 'Kz', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'ARS' => ['name' => 'Argentina Peso', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'AUD' => ['name' => 'Australia Dollar', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'AWG' => ['name' => 'Aruba Guilder', 'symbol' => 'ƒ', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'AZN' => ['name' => 'Azerbaijan New Manat', 'symbol' => 'ман', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'BAM' => ['name' => 'Bosnia and Herzegovina Convertible Marka', 'symbol' => 'KM', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'BBD' => ['name' => 'Barbados Dollar', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'BDT' => ['name' => 'Bangladeshi taka', 'symbol' => '৳', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'BGN' => ['name' => 'Bulgaria Lev', 'symbol' => 'лв', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'BHD' => ['name' => 'Bahraini Dinar', 'symbol' => '.د.ب', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'BIF' => ['name' => 'Burundi Franc', 'symbol' => 'FBu', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'BMD' => ['name' => 'Bermuda Dollar', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'BND' => ['name' => 'Brunei Darussalam Dollar', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'BOB' => ['name' => 'Bolivia Boliviano', 'symbol' => '$b', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'BRL' => ['name' => 'Brazil Real', 'symbol' => 'R$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'BSD' => ['name' => 'Bahamas Dollar', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'BTN' => ['name' => 'Ngultrum', 'symbol' => 'Nu.', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'BWP' => ['name' => 'Botswana Pula', 'symbol' => 'P', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'BYR' => ['name' => 'Belarus Ruble', 'symbol' => 'p.', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'BZD' => ['name' => 'Belize Dollar', 'symbol' => 'BZ$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'CDF' => ['name' => 'Congolese Franc', 'symbol' => 'FC', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'CHF' => ['name' => 'Switzerland Franc', 'symbol' => 'CHF', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'CLP' => ['name' => 'Chile Peso', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'CNY' => ['name' => 'China Yuan Renminbi', 'symbol' => '¥', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'COP' => ['name' => 'Colombia Peso', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'CRC' => ['name' => 'Costa Rica Colon', 'symbol' => '₡', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'CUP' => ['name' => 'Cuba Peso', 'symbol' => 'CUP', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'CVE' => ['name' => 'Cabo Verde Escudo', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'CZK' => ['name' => 'Czech Republic Koruna', 'symbol' => 'Kč', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'DJF' => ['name' => 'Djibouti Franc', 'symbol' => 'Fdj', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'DKK' => ['name' => 'Denmark Krone', 'symbol' => 'kr', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'DOP' => ['name' => 'Dominican Republic Peso', 'symbol' => 'RD$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'DZD' => ['name' => 'Algerian Dinar', 'symbol' => 'دج', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'EGP' => ['name' => 'Egypt Pound', 'symbol' => '£', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'ETB' => ['name' => 'Ethiopian Birr', 'symbol' => 'Br', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'FJD' => ['name' => 'Fiji Dollar', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'FKP' => ['name' => 'Falkland Islands (Malvinas) Pound', 'symbol' => '£', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'GBP' => ['name' => 'United Kingdom Pound', 'symbol' => '£', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'GEL' => ['name' => 'Lari', 'symbol' => 'ლ', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'GHS' => ['name' => 'Ghana Cedi', 'symbol' => '¢', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'GIP' => ['name' => 'Gibraltar Pound', 'symbol' => '£', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'GMD' => ['name' => 'Dalasi', 'symbol' => 'D', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'GNF' => ['name' => 'Guinea Franc', 'symbol' => 'FG', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'GTQ' => ['name' => 'Guatemala Quetzal', 'symbol' => 'Q', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'GYD' => ['name' => 'Guyana Dollar', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'HKD' => ['name' => 'Hong Kong Dollar', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'HNL' => ['name' => 'Honduras Lempira', 'symbol' => 'L', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'HRK' => ['name' => 'Croatia Kuna', 'symbol' => 'kn', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'HTG' => ['name' => 'Gourde', 'symbol' => 'G', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'HUF' => ['name' => 'Hungary Forint', 'symbol' => 'Ft', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'IDR' => ['name' => 'Indonesia Rupiah', 'symbol' => 'Rp', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'ILS' => ['name' => 'Israel Shekel', 'symbol' => '₪', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'INR' => ['name' => 'India Rupee', 'symbol' => '₹', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'IQD' => ['name' => 'Iraqi Dinar', 'symbol' => 'ع.د', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'IRR' => ['name' => 'Iran Rial', 'symbol' => '﷼', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'ISK' => ['name' => 'Iceland Krona', 'symbol' => 'kr', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'JMD' => ['name' => 'Jamaica Dollar', 'symbol' => 'J$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'JOD' => ['name' => 'Jordanian Dinar', 'symbol' => 'JD', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'JPY' => ['name' => 'Japan Yen', 'symbol' => '¥', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'KES' => ['name' => 'Kenyan Shilling', 'symbol' => 'KSh', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'KGS' => ['name' => 'Kyrgyzstan Som', 'symbol' => 'лв', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'KHR' => ['name' => 'Cambodia Riel', 'symbol' => '៛', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'KMF' => ['name' => 'Comoro Franc', 'symbol' => 'CF', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'KPW' => ['name' => 'Korea (North) Won', 'symbol' => '₩', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'KRW' => ['name' => 'Korea (South) Won', 'symbol' => '₩', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'KWD' => ['name' => 'Kuwaiti Dinar', 'symbol' => 'د.ك', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'KYD' => ['name' => 'Cayman Islands Dollar', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'KZT' => ['name' => 'Kazakhstan Tenge', 'symbol' => 'лв', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'LAK' => ['name' => 'Laos Kip', 'symbol' => '₭', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'LBP' => ['name' => 'Lebanon Pound', 'symbol' => '£', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'LKR' => ['name' => 'Sri Lanka Rupee', 'symbol' => '₨', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'LRD' => ['name' => 'Liberia Dollar', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'LSL' => ['name' => 'Loti', 'symbol' => 'L', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'LYD' => ['name' => 'Libyan Dinar', 'symbol' => 'ل.د', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'MAD' => ['name' => 'Moroccan Dirham', 'symbol' => 'د.م.', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'MDL' => ['name' => 'Moldovan Leu', 'symbol' => 'L', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'MKD' => ['name' => 'Macedonia Denar', 'symbol' => 'ден', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'MMK' => ['name' => 'Kyat', 'symbol' => 'K', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'MNT' => ['name' => 'Mongolia Tughrik', 'symbol' => '₮', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'MOP' => ['name' => 'Pataca', 'symbol' => 'MOP$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'MUR' => ['name' => 'Mauritius Rupee', 'symbol' => '₨', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'MVR' => ['name' => 'Rufiyaa', 'symbol' => '.ރ', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'MWK' => ['name' => 'Kwacha', 'symbol' => 'MK', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'MXN' => ['name' => 'Mexico Peso', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'MYR' => ['name' => 'Malaysia Ringgit', 'symbol' => 'RM', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'MZN' => ['name' => 'Mozambique Metical', 'symbol' => 'MT', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'NAD' => ['name' => 'Namibia Dollar', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'NGN' => ['name' => 'Nigeria Naira', 'symbol' => '₦', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'NIO' => ['name' => 'Nicaragua Cordoba', 'symbol' => 'C$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'NOK' => ['name' => 'Norway Krone', 'symbol' => 'kr', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'NPR' => ['name' => 'Nepal Rupee', 'symbol' => '₨', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'NZD' => ['name' => 'New Zealand Dollar', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'OMR' => ['name' => 'Oman Rial', 'symbol' => '﷼', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'PAB' => ['name' => 'Panama Balboa', 'symbol' => 'B/.', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'PEN' => ['name' => 'Peru Nuevo Sol', 'symbol' => 'S/.', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'PGK' => ['name' => 'Kina', 'symbol' => 'K', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'PHP' => ['name' => 'Philippines Peso', 'symbol' => '₱', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'PKR' => ['name' => 'Pakistan Rupee', 'symbol' => '₨', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'PLN' => ['name' => 'Poland Zloty', 'symbol' => 'zł', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'PYG' => ['name' => 'Paraguay Guarani', 'symbol' => 'Gs', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'QAR' => ['name' => 'Qatar Riyal', 'symbol' => '﷼', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'RON' => ['name' => 'Romania New Leu', 'symbol' => 'lei', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'RSD' => ['name' => 'Serbia Dinar', 'symbol' => 'Дин.', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'RUB' => ['name' => 'Russia Ruble', 'symbol' => '₽', 'direction' => 'right', 'decimal_sep' => ',', 'thousand_sep' => '.'],
        'RWF' => ['name' => 'Rwanda Franc', 'symbol' => 'ر.س', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'SAR' => ['name' => 'Saudi Arabia Riyal', 'symbol' => '﷼', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'SBD' => ['name' => 'Solomon Islands Dollar', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'SCR' => ['name' => 'Seychelles Rupee', 'symbol' => '₨', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'SDG' => ['name' => 'Sudanese Pound', 'symbol' => '£', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'SEK' => ['name' => 'Sweden Krona', 'symbol' => 'kr', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'SGD' => ['name' => 'Singapore Dollar', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'SOS' => ['name' => 'Somalia Shilling', 'symbol' => 'S', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'SRD' => ['name' => 'Suriname Dollar', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'THB' => ['name' => 'Thai Baht', 'symbol' => '฿', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'TJS' => ['name' => 'Tajikistani Somoni', 'symbol' => 'TJS', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'TMT' => ['name' => 'Turkmenistani Manat', 'symbol' => 'm', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'TND' => ['name' => 'Tunisian Dinar', 'symbol' => 'د.ت', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'TRY' => ['name' => 'Turkish Lira', 'symbol' => '₺', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'TTD' => ['name' => 'Trinidad and Tobago Dollar', 'symbol' => '$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'TWD' => ['name' => 'New Taiwan Dollar', 'symbol' => 'NT$', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'UAH' => ['name' => 'Ukrainian Hryvnia', 'symbol' => '₴', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'UGX' => ['name' => 'Ugandan Shilling', 'symbol' => 'USh', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'UYU' => ['name' => 'Uruguayan Peso', 'symbol' => '$U', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'UZS' => ['name' => 'Uzbekistani Som', 'symbol' => 'лв', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'VND' => ['name' => 'Vietnamese Dong', 'symbol' => '₫', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'YER' => ['name' => 'Yemeni Rial', 'symbol' => '﷼', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
        'ZAR' => ['name' => 'South African Rand', 'symbol' => 'R', 'direction' => 'left', 'decimal_sep' => '.', 'thousand_sep' => ','],
    ];
}